### ISSUE TITLE
Would be nice to have a docker image

### ISSUE THREAD

**Issue by botzill** [ramiroaisen/raven-webmail#1]
Hi.

I was wondering if you plan a docker image and hosted on docker hub to be able to test this faster? 

Thx.

**Comment by ramiroaisen** [comment]
Yes that would be nice, I'm not too much familiarized with docker do

**Comment by ramiroaisen** [comment]
> Hi.
> 
> I was wondering if you plan a docker image and hosted on docker hub to be able to test this faster?
> 
> Thx.

Are you willing to guide me in making the docker image?
Thanks!

**Comment by stonewjr** [comment]
I try to install on windows10 but not working what i missing!

**Comment by bogdaniel** [comment]
Hello in the next couple of days I will create a docker Image and post it here.

**Comment by bogdaniel** [comment]
> > Hi.
> > I was wondering if you plan a docker image and hosted on docker hub to be able to test this faster?
> > Thx.
> 
> Are you willing to guide me in making the docker image? Thanks!

Hello I've created an image here https://github.com/bogdaniel/docker-raven-webmail
