### ISSUE TITLE
Do NOT install this on a server you care about

### ISSUE THREAD

**Issue by jhayesdev** [ramiroaisen/raven-webmail#19]
Seriously, just don't. If you're running a reasonably up-to-date stack and you try to install this, it'll steal your packages, and probably your lunch money too. Ok, I admit, I am node noob, and I should have known better than to mix and match prod and testing on the same environment, I should be using a lot more containers, shame on me for this one. But you've all been warned.

**Comment by ramiroaisen** [comment]
That is not true, what are youm talking about?
