### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by ValoreAreaIT** [ramiroaisen/raven-webmail#24]
Hi! I made an Italian localization file
[it.zip](https://github.com/ramiroaisen/raven-webmail/files/8563740/it.zip)
.

**Comment by ramiroaisen** [comment]
Great. I will add it to the available locales as soon as I can. Thank you very much!

**Comment by ramiroaisen** [comment]
@ValoreAreaIT A couple of keys were added to the base locales to support user signatures. Could you please update your locale and send it again, If you do I'll add it to the available locales for users to use.

**Comment by ValoreAreaIT** [comment]
Here is it!
[it.zip](https://github.com/ramiroaisen/raven-webmail/files/9866909/it.zip)

**Comment by ramiroaisen** [comment]
Thank you very much @ValoreAreaIT the Italian locale is now part of Raven source code in version 1.2.0 at npm. I'll close this issue now.
