### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by ValoreAreaIT** [ramiroaisen/raven-webmail#25]
Hi, there's a way to use a signature when write a new email?

**Comment by ramiroaisen** [comment]
This is my top priority to add, we'll add ir as soon as I can.

**Comment by ramiroaisen** [comment]
@ValoreAreaIT Signature support is now available in the latest release in npm. Version 1.1.3.
You can see more info about this in the Changelog in the README.
I'll will close this issue now, thanks!
