### ISSUE TITLE
I'm an old-timer with Linux but having trouble with wildduck and raven on Ubuntu server 20.04

### ISSUE THREAD

**Issue by WakeReality** [ramiroaisen/raven-webmail#47]
It isn't really clear to me if Redis and mongodb need to be from Ubuntu 20.04 repository or source, or what. I just can't get the install working and I've reformatted my Ubuntu server and tried again 3 times and I can't figure out if I'm missing dependencies or whatnot.

If someone knows a step by step walkthrough of install on Ubuntu 20.04 please share. I will try to create one.

I have a public web server I can give you root access and we can reinstall if you want to help me figure this out.

Merry Christmas, thank you.

**Comment by WakeReality** [comment]
I've made progress. It seems wildduck won't work with mongodb provided by Ubuntu 20.04 and you have to add another repository to get one that wildduck starts with.

I used these instructions:

https://computingforgeeks.com/how-to-install-mongodb-database-on-ubuntu/

**Comment by WakeReality** [comment]
ttsc is invoked in the package.json but isn't listed as a dependency. running this fixed it:

    npm instal ttypescript

**Comment by WakeReality** [comment]
I have wildduck running on a public server: http://server4.zbbs.email/

Can I run raven-webmail on a machine behind NAT router that connects to the wildduck server? I'm still trying to figure out all the components and network ports.

**Comment by ramiroaisen** [comment]
Raven webmail only communicates with wildduck with wildduck's API, the mongodb connections is only used for storing persistent user sessions and doesn't need to be the same mongodb server that's running wildduck.
