### ISSUE TITLE
Installing Raven

### ISSUE THREAD

**Issue by tobsowo** [ramiroaisen/raven-webmail#54]
Can I install on the same server I have WildDuck with latest WildDuck?
Since I have WildDuck Webmail on mail.domain.tld I'll like to have raven-webmail as domain.tld, is this possible to do?

Is there more screenshot that shows the app?

**Comment by ramiroaisen** [comment]
Hello, yes this is possible, you can run both raven and wildduck in the same server without problem, you can use a process  manager to do so... i recommend [pm2](https://pm2.keymetrics.io/)
