### ISSUE TITLE
svelte-kit: not found

### ISSUE THREAD

**Issue by tpimh** [ramiroaisen/raven-webmail#56]
Trying to build raven-webmail, and getting this error:

```
$ run-p 'build:*'
$ tsc --project ./server/tsconfig.json
$ cd app && npm run build && cd ..

> raven-webmail-client@1.0.0 build
> svelte-kit build

sh: svelte-kit: not found
```

**Comment by ramiroaisen** [comment]
Could you please elaborate what actions are you doing before that error.
Also, information about the OS and node versions will be helpful.

**Comment by tpimh** [comment]
I am using Alpine Linux edge with Node v20.13.1 in Docker. Here are the actions I perform:

1. `git clone https://github.com/ramiroaisen/raven-webmail`
2. `cd raven-webmail`
3. `npm i`
4. `npm run build`

The output is the following:
```
/app # git clone https://github.com/ramiroaisen/raven-webmail/
Cloning into 'raven-webmail'...
remote: Enumerating objects: 8545, done.
remote: Counting objects: 100% (457/457), done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 8545 (delta 223), reused 352 (delta 156), pack-reused 8088
Receiving objects: 100% (8545/8545), 18.31 MiB | 8.34 MiB/s, done.
Resolving deltas: 100% (4493/4493), done.
/app # cd raven-webmail/
/app/raven-webmail # npm i
npm WARN deprecated @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need this installed.

> raven-webmail@1.2.1-3 prepare
> ts-patch install -s


added 330 packages, and audited 331 packages in 23s

52 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (8 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
/app/raven-webmail # npm run build

> raven-webmail@1.2.1-3 build
> run-p 'build:*'


> raven-webmail@1.2.1-3 build:app
> cd app && npm run build && cd ..


> raven-webmail@1.2.1-3 build:server
> tsc --project ./server/tsconfig.json


> raven-webmail-client@1.0.0 build
> svelte-kit build

sh: svelte-kit: not found
ERROR: "build:app" exited with 127.
/app/raven-webmail # 
```

Let me know if you need any additional info to replicate the problem!

**Comment by ramiroaisen** [comment]
> I am using Alpine Linux edge with Node v20.13.1 in Docker. Here are the actions I perform:
> 
> 1. `git clone https://github.com/ramiroaisen/raven-webmail`
> 2. `cd raven-webmail`
> 3. `npm i`
> 4. `npm run build`
> 
> The output is the following:
> ```
> /app # git clone https://github.com/ramiroaisen/raven-webmail/
> Cloning into 'raven-webmail'...
> remote: Enumerating objects: 8545, done.
> remote: Counting objects: 100% (457/457), done.
> remote: Compressing objects: 100% (284/284), done.
> remote: Total 8545 (delta 223), reused 352 (delta 156), pack-reused 8088
> Receiving objects: 100% (8545/8545), 18.31 MiB | 8.34 MiB/s, done.
> Resolving deltas: 100% (4493/4493), done.
> /app # cd raven-webmail/
> /app/raven-webmail # npm i
> npm WARN deprecated @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need this installed.
> 
> > raven-webmail@1.2.1-3 prepare
> > ts-patch install -s
> 
> 
> added 330 packages, and audited 331 packages in 23s
> 
> 52 packages are looking for funding
>   run `npm fund` for details
> 
> 13 vulnerabilities (8 moderate, 5 high)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> /app/raven-webmail # npm run build
> 
> > raven-webmail@1.2.1-3 build
> > run-p 'build:*'
> 
> 
> > raven-webmail@1.2.1-3 build:app
> > cd app && npm run build && cd ..
> 
> 
> > raven-webmail@1.2.1-3 build:server
> > tsc --project ./server/tsconfig.json
> 
> 
> > raven-webmail-client@1.0.0 build
> > svelte-kit build
> 
> sh: svelte-kit: not found
> ERROR: "build:app" exited with 127.
> /app/raven-webmail # 
> ```
> 
> Let me know if you need any additional info to replicate the problem!

Theres two packages in raven, the server and the client, seems that you are not running npm install in the client package.

**Comment by tpimh** [comment]
This is strange, since there's only one package.json, I was thinking there's only one package. How should I start raven-webmail correctly?

**Comment by ramiroaisen** [comment]
You can see the README file , there's info about how to build and run locally raven.
That is only for develoment porpouses, for use in production just install from npm `npm install raven-webmail`
