### ISSUE TITLE
I try to install on windows10 but not working what i missing!

### ISSUE THREAD

**Issue by stonewjr** [ramiroaisen/raven-webmail#9]

**Comment by stonewjr** [comment]
sorry I means client rebuild & npm run dev 
not things to happen on screen !

**Comment by stonewjr** [comment]
sounds missing index.html in public folder!
please help

**Comment by ramiroaisen** [comment]
@stonewjr 
Sorry i just see this, how are the steps you are doing to install?

**Comment by ramiroaisen** [comment]
@stonewjr Are you trying to simply use it or you want to be able to edit the source code?

**Comment by stonewjr** [comment]
I want to edit souce and rebuild it


RamiroAisen <notifications@github.com> 於 2021年2月5日 週五 下午11:17寫道：

**Comment by stonewjr** [comment]
I used to svelte but not typescript so I like to learn from your project

Thanks

Stone Wu <stonewjr@gmail.com> 於 2021年2月6日 週六 下午3:25寫道：

**Comment by ramiroaisen** [comment]
@stonewjr I was not able to reproduce the error, are you following all the steps in the README.md?
Please list the steps you're following and the terminal output so I can help you
